apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-car-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-car-app
  template:
    metadata:
      labels:
        app: backend-car-app
    spec:
      containers:
        - name: backend-car-app
          image: atharva25s/backend-car-app:b16c353
          imagePullPolicy: Always
          ports:
            - containerPort: 8000   # change if your app uses a different port
