# ---------------- BACKEND DEPLOYMENT ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-car-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-car-app
  template:
    metadata:
      labels:
        app: backend-car-app
    spec:
      containers:
        - name: backend-car-app
          image: atharva25s/backend-car-app:7f1f287
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
