name: Build and Deploy Backend

permissions:
  contents: write


on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'Deploy backend image')"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -f backend-car-app/Dockerfile -t atharva25s/backend-car-app:$IMAGE_TAG backend-car-app          
          docker push atharva25s/backend-car-app:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Kubernetes deployment image
        run: |
          sed -i "s|image: atharva25s/backend-car-app:.*|image: atharva25s/backend-car-app:${IMAGE_TAG}|" K8s-specifications/deployment.yml

      - name: Commit and push deployment update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add K8s-specifications/deployment.yml
          git commit -m "Deploy backend image ${IMAGE_TAG}"
          git push
